baseURL = "/"
languageCode = "en-us"
title = "St Ives Smiles"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"

[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.svg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Hugo Hero"

  [params.homepage_meta_tags]
    meta_description = "Located in the heart of St Ives Chase for over 30 years, we are a family practice, providing quality dental services for all ages"
    meta_og_title = "St Ives Smiles"
    meta_og_type = "website"
    meta_og_url = "https://main--symphonious-palmier-fc418b.netlify.app"
    meta_og_image = "https://static.wixstatic.com/media/6c0d51_234419f233ce4b649ee9394c73f2256f~mv2.jpg/v1/fill/w_814,h_1220,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/theresafamily-052_JPG.jpg"
    meta_og_description = "Located in the heart of St Ives Chase for over 30 years, we are a family practice, providing quality dental services for all ages."
    meta_twitter_card = "summary"
    meta_twitter_site = "@tbeuzen"
    meta_twitter_creator = "@tbeuzen"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Gallery"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/pages/about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
